[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"

[profile.deployment]
optimizer = true
optimizer_runs = 1000
via_ir=true

[profile.ci-fast]
fuzz = { runs = 500 }
invariant = { runs = 128 }

[profile.ci-fork]
fuzz = { runs = 50 }           # Fewer runs for fork tests
invariant = { runs = 25 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[fuzz]
runs = 1000                   
max_test_rejects = 100000
seed = "0x1"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 16
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[dependencies]
forge-std = "1.9.7"
"@layerzerolabs-lz-evm-protocol-v2" = "3.0.102"
"@layerzerolabs-oft-evm-upgradeable" = "3.1.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
"@layerzerolabs-oapp-evm-upgradeable" = "0.1.2"
"@openzeppelin-contracts" = "5.3.0"
"@layerzerolabs-oapp-evm" = "0.3.2"
"@layerzerolabs-oft-evm" = "3.1.4"
gnsps-solidity-bytes-utils = "0.8.4"
"@layerzerolabs-lz-evm-messagelib-v2" = "3.0.102"

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
